### PR TITLE
Set `tabIndex` on `<body>` to hide tooltip on focus change for iOS + Safari

### LINKED ISSUE #8: Pop up boxes fail to disappear on focus change on mobile 🤙
### Reproduce the bug ⚡️

When interacting with the results section on mobile, press any of the dashed underlined titles.

Note, if you change focus to an interactive or clickable element, the pop up box disappears.

### Suggested improvements 🔨

The pop up box should disappear when focus changes to any element other than the pop up box itself.

### Device and Browser 📱

iPhone, Safari

### PR DESCRIPTION
**Pull request by JamieSlome**
Closes #8

## Summary by CodeRabbit

- **New Features**
	- Added an option to display tooltips in Core Web Vitals graphs.
	- Updated the graph component to conditionally show tooltips based on user interaction.
	- Improved page accessibility by adding a `tabIndex` attribute to enhance keyboard navigation.

### CODE REVIEW

File: app.vue [hunk 1]
```diff
@@ -94,6 +94,9 @@ useFavicon(() => lighthouseStatus.value !== 'pending' && !!domain.value && (ligh
 
 useHead({
   title: () => domain.value ? domain.value : 'page-speed.dev',
+  bodyAttrs: {
+    tabIndex: "0"
```
Comment (danielroe) [inline app.vue:98]:
```suggestion
    tabIndex: '0'
```

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you ❤️
